### ISSUE TITLE
Find a nice way to proxy to upstream modules

### ISSUE THREAD

**Issue by underyx** [kiwicom/kiwi-platform-py#1]
### Structure

A `*` marks proxied modules.

```
├── kw
│   ├── __init__.py
│   └── platform
│       ├── __init__.py
│       ├*─ aiohttp
│       ├*─ requests
│       └── wsgi
│           ├── __init__.py
│           ├── user_agents.py
│           └── deprecations.py
```

### Requirements

- We need to be able to modify (patch) the contents that are imported.
- We want to be nice about the patching though, so ideally we'd modify a local copy of the module.
- The patching functions should be part of the public API so people can do it themselves
- We need to avoid adding the modules as package dependencies so that requests users aren't forced to install aiohttp. Importing a non-installed patched module should raise `ImportError`
- Since a major release could break compatibility, we should set the version range specifier in `extras_require`, so that people can install a known compatible version via `kiwi-platform[flask,requests]`.

**Comment by paveldedik** [comment]
This can be closed right?

I'm going to close this, feel free to open again.
