### ISSUE TITLE
aiohttp: Corretly mock requests in tests

### ISSUE THREAD

**Issue by paveldedik** [kiwicom/kiwi-platform-py#26]
Currently, we aren't mocking in some aiohttp tests and are making actual requests to `www.kiwi.com`. We should avoid that even in tests.

**Comment by paveldedik** [comment]
I successfully used [aioresponses](https://github.com/pnuckowski/aioresponses) in some of the tests. The problem is, that when the `aiohttp.ClientSession._request` is patched with `wrapt`, the mocking with `aioresponses` doesn't work.

**Comment by Stranger6667** [comment]
There is a couple of alternatives:

- [pytest-recording](https://github.com/kiwicom/pytest-recording) that works on top of [vcr.py](https://github.com/kevin1024/vcrpy) package (cassettes-based testing, which is still mocking)
- [pytest-httpbin](https://github.com/kevin1024/pytest-httpbin) that will run an instance of `httpbin` as a pytest fixture - requests could go to the server that runs locally (real network requests)
